### PR TITLE
stream functions and classes refactoring

### PR DESCRIPTION
**Pull request by jerabekjak**
there is room for improvement:

- [x]  can be improved by reducing the size of some variables see #355  https://github.com/storm-fsv-cvut/smoderp2d/blob/cd4352fc4fac7c12d681b5a3083f8f83052e4f8b/smoderp2d/core/stream.py#L10

- [x] the compute_h needs improvement, the Newton method is not efficient https://github.com/storm-fsv-cvut/smoderp2d/blob/cd4352fc4fac7c12d681b5a3083f8f83052e4f8b/smoderp2d/stream_functions/stream_f.py#L27 

maybe something else comes up ...

### CODE REVIEW

**Comment by pesekon2** [comment]
> can be improved by reducing the size of some variables see https://github.com/storm-fsv-cvut/smoderp2d/issues/355

Let's solve these in two different PRs. Work on the Newton solver and on the variables simplification is not necessarily connected and splitting it could make both get to master faster.

**Comment by jerabekjak** [comment]
@pesekon2 OK. I only check the newton solver here. I'll make a list of variables to de-matrixed in #355 as suggested.

**Comment by jerabekjak** [comment]
Work continue here #364

**Comment by jerabekjak** [comment]
@pesekon2  The test fail due to different rounding in "new" calculations of water level in streams. In graphs the ref and PR data looks same - ok.

**Comment by jerabekjak** [comment]
@pesekon2  for some reason the save files for gistest disappeared so I had to added them in [8fe5b84](https://github.com/storm-fsv-cvut/smoderp2d/pull/356/commits/8fe5b84dfc884387d87d4a761039ab7c4df28415)

**Review by pesekon2 — APPROVED** [review]

**Pull request merged**
