### PR TITLE
infiltration calculated from cumulative philips

### PR DESCRIPTION
**Pull request by jerabekjak**
Infiltration was calculated based on the cumulative philips formula. The infiltration was shown to be closer to the analytical Philips solution.

### CODE REVIEW

**Comment by kavkapet** [comment]
MERGE WHEN COMPUTATIONS ARE FINISHED !!!

**Comment by pesekon2** [comment]
@jerabekjak, @kavkapet, @landam : I have solved the conflicts to make it work with SMODERP 2.0. The tests are failing now, but this is expected as the infiltration computation has changed. Could you please review the change and the new results if they make more sense than the previous ones? If it is so, I would recommend to update the test reference data to the new values and merge it.

**Comment by jerabekjak** [comment]
Bellow are results from the infitlration rate-based  and cumulative-based infiltration calculation (this PR) (quick test only). In both cases there is some error in comparison to analysitical solution. However in rate-based formula the error is increasing with time while in cumulative-based calculation the error is still the same. Therefore I think that cumulative-based infiltration in PR is more accurate and therefore this PR can be merged.  And the reference results replaced. 

[point001-intenzitneinfiltrace.ods](https://github.com/storm-fsv-cvut/smoderp2d/files/13178601/point001-intenzitneinfiltrace.ods)
[point001-kumulativneinfiltrace.ods](https://github.com/storm-fsv-cvut/smoderp2d/files/13178602/point001-kumulativneinfiltrace.ods)

**Comment by pesekon2** [comment]
@jerabekjak: Is a change like this (the first line) okay? It seems pretty extreme to me, even when compared with the following lines:

image

**Comment by pesekon2** [comment]
After our live discussion, I am merging the PR. If something gets wrong with the computation afterwards, blame those who did not review the result changes.

**Pull request merged**
