### PR TITLE
reach transformed from list to dict 

### PR DESCRIPTION
**Pull request by landam**
See #81

### CODE REVIEW

**Comment by jerabekjak** [comment]
@landam 
I've tried it in an error when I tried it in ArcGis. I error was raised after data preparation, so I do not know if it suppose to be done. Here is the traceback. 
```
Traceback (most recent call last):
  File "C:\Users\jerabj11\Documents\GitHub\smoderp2d\bin\start-smoderp2d.py", line 20, in <module>
    sys.exit(runner.run())
  File "C:\Users\jerabj11\Documents\GitHub\smoderp2d\bin\..\smoderp2d\__init__.py", line 80, in run
    runoff = Runoff(self._provider)
  File "C:\Users\jerabj11\Documents\GitHub\smoderp2d\bin\..\smoderp2d\runoff.py", line 215, in __init__
    True
  File "C:\Users\jerabj11\Documents\GitHub\smoderp2d\bin\..\smoderp2d\io_functions\hydrographs.py", line 142, in write_hydrographs_record
    surface.return_stream_str_vals(l, m, sep, dt, Globals.extraOut),
  File "C:\Users\jerabj11\Documents\GitHub\smoderp2d\bin\..\smoderp2d\core\stream.py", line 136, in return_stream_str_vals
    r = self.reach[fid]
KeyError: 3 
```

**Comment by jerabekjak** [comment]
@landam 
have a look at the commit  cae4e1bffcbae7d7b955ad13cb27e1d92f075abb
it should solve the error from the comment https://github.com/storm-fsv-cvut/smoderp2d/pull/82#issuecomment-622002070.
Nothing should change for grass (hopefully)...

**Comment by landam** [comment]
> @landam
> have a look at the commit [cae4e1b](https://github.com/storm-fsv-cvut/smoderp2d/commit

hm, strange, we are using keys, not indices, I wonder why you need to increase a key by one. That's strange, will take a look.

**Comment by landam** [comment]
> hm, strange, we are using keys, not indices, I wonder why you need to increase a key by one. That's strange, will take a look.

@jerabekjak @kavkapet @pesekon2 ArcGIS is mysterious software, compare ObjectID in the attribute table and reported by arcpy

**Comment by landam** [comment]
> @jerabekjak @kavkapet @pesekon2 ArcGIS is mysterious software, compare ObjectID in the attribute table and reported by arcpy

The mystery was caused by our @kalator code :-) Fixed in https://github.com/storm-fsv-cvut/smoderp2d/pull/82/commits/a4021c8fba995a0e09535042897be95076b6d846

**Comment by landam** [comment]
@jerabekjak Please test.

**Comment by landam** [comment]
Before merging we should test whether these changes do not affect results, see https://github.com/ctu-fgis/2020-f-smoderp2d/issues/4

**Comment by landam** [comment]
> The results are (also see bellow): xml differs due to different time stamp (no problem). The only rasters which differ are the ones with FID data (which is correct), the rest of rasters are the same (good!). Error is in point004 and point005. Have a look bellow. Need fix.

Good catch. Fixed in 29dd72b.

**Comment by landam** [comment]
@jerabekjak Please review also places where is used 1000 value. Some of them should be changed to `Globals.streams_flow_inc`.

```
smoderp2d/io_functions/hydrographs.py
54:                if Globals.get_mat_stream_reach(l, m) >= 1000:

smoderp2d/io_functions/post_proc.py
71:            if (finState[i][j] >= 1000):
130:                # if (finState[i][j] >= 1000) :
154:                # if (finState[ii][jj]>=1000):
256:                # if (finState[i][j] >= 1000) :
267:                # if (finState[i][j] >= 1000) :

smoderp2d/core/vegetation.py
26:        mat_pi = Globals.get_mat_pi() / 1000.0

smoderp2d/core/general.py
186:    streams_flow_inc = 1000

smoderp2d/processes/rainfall.py
71:                    y1 = float(z[1]) / 1000.0  # prevod na metry

smoderp2d/providers/arcgis/stream_preparation.py
202:        1000 in return numpy array) or not (number 0 in return numpy
218:        #     "NoDataValue 1000", stream_seg, "DATA"

smoderp2d/providers/arcgis/data_preparation.py
113:            dem_copy, "VALUE", "-100000 100000 1", dem_mask, "DATA"

smoderp2d/providers/grass/stream_preparation.py
203:        1000 in return numpy array) or not (number 0 in return numpy
221:               # expression='{o} = if(isnull({i}), 1000, {i})'.format(

smoderp2d/providers/base/output.py
36:                    if fs[i][j] >= 1000:

smoderp2d/providers/base/__init__.py
212:        Globals.mat_reten = -1.0 * data['mat_reten'] / 1000
395:                if finState[i][j] >= 1000:
406:                if  int(surface_array[i][j].state) >= 1000 :

smoderp2d/providers/base/data_preparation.py
423:                        hcrit_tau = hcrit_v = hcrit_flux = 1000
```

It's quite clear here:
```
95:                if finState[i][j] >= 1000:
406:                if  int(surface_array[i][j].state) >= 1000 :
```

But what about other occurrencies?

**Comment by jerabekjak** [comment]
The check list is based on https://github.com/storm-fsv-cvut/smoderp2d/pull/82#issuecomment-622561674. I'll review it as soon as possible. 

- [ ] smoderp2d/core/general.py:186:    streams_flow_inc = 1000
- [ ] smoderp2d/core/vegetation.py:26:        mat_pi = Globals.get_mat_pi() / 1000.0
- [ ] smoderp2d/io_functions/hydrographs.py:54:                if Globals.get_mat_stream_reach(l, m) >= 1000:
- [ ] smoderp2d/io_functions/post_proc.py:71:            if (finState[i][j] >= 1000):
- [ ] smoderp2d/io_functions/post_proc.py:130:                # if (finState[i][j] >= 1000) :
- [ ] smoderp2d/io_functions/post_proc.py:154:                # if (finState[ii][jj]>=1000):
- [ ] smoderp2d/io_functions/post_proc.py:256:                # if (finState[i][j] >= 1000) :
- [ ] smoderp2d/io_functions/post_proc.py:267:                # if (finState[i][j] >= 1000) :
- [ ] smoderp2d/processes/rainfall.py:71:                    y1 = float(z[1]) / 1000.0  # prevod na metry
- [ ] smoderp2d/providers/arcgis/data_preparation.py:113:            dem_copy, "VALUE", "-100000 100000 1", dem_mask, "DATA"
- [ ] smoderp2d/providers/arcgis/stream_preparation.py:202:        1000 in return numpy array) or not (number 0 in return numpy
- [ ] smoderp2d/providers/arcgis/stream_preparation.py:218:        #     "NoDataValue 1000", stream_seg, "DATA"
- [ ] smoderp2d/providers/base/__init__.py:212:        Globals.mat_reten = -1.0 * data['mat_reten'] / 1000
- [ ] smoderp2d/providers/base/__init__.py:395:                if finState[i][j] >= 1000:
- [ ] smoderp2d/providers/base/__init__.py:406:                if  int(surface_array[i][j].state) >= 1000 :
- [ ] smoderp2d/providers/base/data_preparation.py:423:                        hcrit_tau = hcrit_v = hcrit_flux = 1000
- [ ] smoderp2d/providers/base/output.py:36:                    if fs[i][j] >= 1000:
- [ ] smoderp2d/providers/grass/stream_preparation.py:203:        1000 in return numpy array) or not (number 0 in return numpy
- [ ] smoderp2d/providers/grass/stream_preparation.py:221:               # expression='{o} = if(isnull({i}), 1000, {i})'.format(
[

**Comment by landam** [comment]
> The check list is based on [#82 (comment)](https://github.com/storm-fsv-cvut/smoderp2d/pull/82#issuecomment-622561674). I'll review it as soon as possible.

@jerabekjak If you need more time, than we could solve it in separated PR. What do you thing? I would prefer to merge this PR ASAP if possible.

**Comment by jerabekjak** [comment]
> > The check list is based on [#82 (comment)](https://github.com/storm-fsv-cvut/smoderp2d/pull/82#issuecomment-622561674). I'll review it as soon as possible.
> 
> @jerabekjak If you need more time, than we could solve it in separated PR. What do you thing? I would prefer to merge this PR ASAP if possible.

Ok. Merge approged;) I can do the check list in https://github.com/storm-fsv-cvut/smoderp2d/pull/82#issuecomment-623385150 in separate PR.

**Comment by landam** [comment]
> > > The check list is based on [#82 (comment)](https://github.com/storm-fsv-cvut/smoderp2d/pull/82#issuecomment-622561674). I'll review it as soon as possible.
> > 
> > 
> > @jerabekjak If you need more time, than we could solve it in separated PR. What do you thing? I would prefer to merge this PR ASAP if possible.
> 
> Ok. Merge approved;) I can do the checklist in [#82 (comment)](https://github.com/storm-fsv-cvut/smoderp2d/pull/82#issuecomment-623385150) in separate PR.

See related issue: https://github.com/storm-fsv-cvut/smoderp2d/issues/83

**Pull request merged**
