### PR TITLE
Fix broken profile1D

### PR DESCRIPTION
**Pull request by landam**
- [x] fix failures (#160)
- [x] add profile1d into tests

### CODE REVIEW

**Comment by pesekon2** [comment]
> Currently it fails on:
> 
> ```python
> Traceback (most recent call last):
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/bin/start-profile1d.py", line 15, in <module>
>     start_smoderp2d()
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/bin/start.py", line 11, in start_smoderp2d
>     sys.exit(runner.run())
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/bin/../smoderp2d/__init__.py", line 105, in run
>     runoff.save_output()
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/bin/../smoderp2d/runoff.py", line 441, in save_output
>     self.provider.postprocessing(self.cumulative, self.surface.arr,
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/bin/../smoderp2d/providers/profile1d/__init__.py", line 402, in postprocessing
>     [0 if i.state == 0 else 1 for i in surface_array.flatten()]
> AttributeError: 'SurArrs' object has no attribute 'flatten'
> ```

Fixed in [9f41919](https://github.com/storm-fsv-cvut/smoderp2d/pull/163/commits/9f419197a5c9bac3cdace67ade875be299424a30)

**Comment by landam** [comment]
One small issue:

```
2023-05-04 17:12:35,031 - SMODERP2D - INFO - Corrected time step is [[30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]
 [30.0]] [s] - [runoff:178]
```

Need to be array?
Values will be always duplicated?

**Comment by pesekon2** [comment]
@landam: Fixed in [d85ba28](https://github.com/storm-fsv-cvut/smoderp2d/pull/163/commits/d85ba2857030b29aa7375f4591b8bc20042d3842). 

As far as I know, it doesn't need to be an array. And I would like to change it later but it is modified in different ways on too many places in the code so it wasn't very straight-forward to change that behaviour and I always got an error in some special setting. But I would like to change that later.

**Comment by pesekon2** [comment]
- [ ] Tests for python 2.7 are failing. 
- [ ] I would support a special test for profile1d for better and more detailed error reviews

**Review by pesekon2 — APPROVED** [review]

**Pull request merged**
