### PR TITLE
QGIS plugin new generation

### PR DESCRIPTION
**Pull request by landam**
Tasks:

- [x] run computation in separated thread
- [x] redirect messages to new tab "SMODERP2D"
- [x] add progress bar (push message bar) [optional]
- [x] GRASS location CRS derived from QGIS project
- [x] data preparation runs repeatedly (see 98c3dc2), but computation hangs on second run
- [x] set QGIS to run with GRASS 8.3 (see https://github.com/storm-fsv-cvut/smoderp2d/pull/197#issuecomment-1618217824, TBD: test also on MS Windows)
- [x] solve problem with dem10m CRS (see 379a24ad90512a6ed1a91c2c8f1e180d71c26ca7)
- [ ] avoid cmd blinking windows

### CODE REVIEW

**Comment by landam** [comment]
QGIS settings:

image

**Comment by pesekon2** [comment]
> QGIS settings
> 

Still not able to run the plugin outside of GRASS. 

```
             ImportError: Could not load grass_gis.8.3.
             
             
             Traceback (most recent call last):
              File "/home/ondrej/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/smoderp_2D_dockwidget.py", line 67, in run
              runner = QGISRunner()
              ^^^^^^^^^^^^
              File "/home/ondrej/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/../../../smoderp2d/__init__.py", line 169, in __init__
              super().__init__()
              File "/home/ondrej/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/../../../smoderp2d/__init__.py", line 44, in __init__
              provider_class = self._provider_factory()
              ^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/ondrej/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/../../../smoderp2d/__init__.py", line 53, in _provider_factory
              from smoderp2d.providers.grass import GrassGisProvider
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/ondrej/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/../../../smoderp2d/providers/grass/__init__.py", line 11, in 
              from grass.pygrass.gis.region import Region
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/ondrej/workspace/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/gis/__init__.py", line 19, in 
              import grass.lib.gis as libgis
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/ondrej/workspace/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/lib/gis.py", line 30, in 
              _libs["grass_gis.8.3"] = load_library("grass_gis.8.3")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/ondrej/workspace/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/lib/ctypes_loader.py", line 105, in __call__
              raise ImportError("Could not load %s." % libname)
             ImportError: Could not load grass_gis.8.3
```

**Comment by pesekon2** [comment]
The second run does not hang on, it is just extremely slow.

**Comment by landam** [comment]
> > QGIS settings
> 
> Still not able to run the plugin outside of GRASS.

@pesekon2 You are right, setting up custom variables doesn't work :-( Workaround:

```sh
QGIS_PLUGINPATH=`pwd`/bin/qgis GISBASE=/home/martin/src/grass/dist.x86_64-pc-linux-gnu LD_LIBRARY_PATH=/home/martin/src/grass/dist.x86_64-pc-linux-gnu/lib qgis tests/data/qgis_project.qgz
```

**Comment by landam** [comment]
> The second run does not hang on, it is just extremely slow.

@pesekon2 Any progress also in this issue?

**Comment by pesekon2** [comment]
> > The second run does not hang on, it is just extremely slow.
> 
> @pesekon2 Any progress also in this issue?

@landam: Not yet. But I think we should first solve why the per cent computation runs backwards for the second run (only the data preparation part). Not only it is probably somehow against the second law of thermodynamics, but it could be somehow connected.

**Comment by pesekon2** [comment]
@landam: I have solved the progress problem and it was not connected to that. 

However, I found a thing that could possibly be the cause: During the second run, some of the globals and GridGlobals (surely `extraOut`, `streams_flow_inc`, `slope_width`, `masks`... I haven't checked all of them) are already set from the first run. I can imagine that it causes some unwanted changes during the second run. 

The results of the second run also differ from the first ones.

**Pull request merged**
