### PR TITLE
Update CI workflow (Python 3.12 and NumPy 1.26.4)

### PR DESCRIPTION
**Pull request by landam**
This PR updates:

- Python 3.11 to 3.12 (current)
- NumPy to 1.26.4 (current) for 3.12 (these versions are used in 
 OSGeo4W)

Additionally also other requirements have been fixed:

- configparser to 7.0.0
- pytest to 8.2.2
- matplotlib to 3.9.0
- scipy to 1.11.3

Support for Python2.7 removed.

### CODE REVIEW

**Comment by landam** [comment]
@pesekon2 What about removing py2.7 workflow?

**Comment by pesekon2** [comment]
> @pesekon2 What about removing py2.7 workflow?

@landam: I support this idea. It is commented at this stage but I support removing it completely.

**Comment by landam** [comment]
> > @pesekon2 What about removing py2.7 workflow?
> 
> @landam: I support this idea. It is commented at this stage but I support removing it completely.

@pesekon2 Please clarify. I haven't found any commented code blocks related PY2.7. Meanwhile I removed `requirements2.7.txt`.

**Comment by pesekon2** [comment]
> > @landam: I support this idea. It is commented at this stage but I support removing it completely.
> 
> @pesekon2 Please clarify. I haven't found any commented code blocks related PY2.7. Meanwhile I removed `requirements2.7.txt`.

@landam: Sorry, I was apparently wrong and the commented blocks were already removed. Thumbs up for the deletion of the 2.7 requirements, though.

**Review by pesekon2 — APPROVED** [review]

**Pull request merged**
