### PR TITLE
support commas as decimal separator in rainfall

### PR DESCRIPTION
**Pull request by pesekon2**

### CODE REVIEW

**Comment by jerabekjak** [comment]
A dont see any benefit of such a change. 
a simle example:
in `master` two columns in rainfall file like `20 3.1` will work. Also if there is more spaces or even tab. It still works.  
You propose to put comma as a separator. The proposed changes `z = line.replace(',', '.').split()` should work how?
`20, 3.1` become `20. 3.1` and then it is splited with what?
It may have some benefits for the WPS or for downloading rainfall data from rain.server. For usage with the other providers. I do not see any benefit.

**Comment by pesekon2** [comment]
The request for this PR came from @kavkapet. He has got some students to test the code and a lot of them tried to use a comma as a decimal separator (i.e. not to divide two values, but in the sense that `3.1 == 3,1`). It failed as we did not expect that.

I have created just this PR instead of pushing the change to `master` because I am not sure if we want to support it. I am actually not in favor to do so, but wanted to hear also you. 

And to answer the question you have raised:

> `20, 3.1` become `20. 3.1` and then it is splited with what?

This one would be split into 20.0 and 3.1. That would work. But having `20,3.1` would fail as it would be changed into `20.3.1`. Another example is `20.0, 3.1` (changed to `20.0. 3.1`)

**Comment by jerabekjak** [comment]
Ok, sorry! Got it!
I should not review pull requests before I have a coffee in the morning.

**Review by jerabekjak — APPROVED** [review]

**Comment by pesekon2** [comment]
Although with this PR, the commas would be supported, stuff like `20.0, 3.1` would still break it. And I still do not like the idea of commas so much as it is not very systematic. Therefore, I propose not to support commas as decimal separators, but instead raise a warning or an error when the user wants to. So the code would not crash somewhere when parsing or computing, but would tell the user "no no no" instead.

**Comment by landam** [comment]
> not like the idea of commas so much as it is not very systematic. Therefore, I propose not to support commas as decimal separators, but instead raise a warning or an error when the user wants to. So the code would not crash somewhere when parsing or computing, but would tell the user "no no no" instead. What do you think?

make sense to me. @pesekon2 Are you going to implemented within this PR?

**Comment by pesekon2** [comment]
As this PR's title is saying something else ("support commas as decimal separator in rainfall"), I think that the cleaner way to do so is to close this PR and open a new one with that. I can take care of that.

**Pull request closed without merging**
