### PR TITLE
Batch processing

### PR DESCRIPTION
**Pull request by landam**
Tasks:
- [x] Shell script
- [x] Bat script
- [x] Test QGIS plugin 
- [x] Update manual (see https://github.com/storm-fsv-cvut/smoderp2d-manual/pull/13)
- [x] Tested by @kavkapet 
- [x] Fix QGIS plugin history handling

### CODE REVIEW

**Review by pesekon2 — CHANGES_REQUESTED** [review]
When I run this branch in QGIS, I get the following warning: `WARNING    Failed to historical item (see logs for details)`

And indeed, it is not added to the history tab.

**Comment by landam** [comment]
@pesekon2 Are you sure that's it related to this PR? I will check it later.

**Comment by landam** [comment]
This could be caused (wild guess) by None assigned to points/streams.

**Comment by landam** [comment]
> @pesekon2 Are you sure that's it related to this PR? I will check it later.

I can confirm that this bug was introduced by this PR.

**Comment by pesekon2** [comment]
Now I get `2024-05-24T09:34:13     WARNING    TypeError: cannot pickle 'QgsRasterLayer' object` when I ran it in QGIS.

Then I turned off QGIS, turned it on, and now I cannot even open the SMODERP2D plugin, getting the following error:

```
An error has occurred while executing Python code: 

TypeError: unable to convert a C++ 'QVariantList' instance to a Python object 
Traceback (most recent call last):
  File "/home/pesek/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/smoderp_2D.py", line 210, in run
    self.dockwidget = Smoderp2DDockWidget()
  File "/home/pesek/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/smoderp_2D_dockwidget.py", line 188, in __init__
    self.retranslateUi()
  File "/home/pesek/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/smoderp_2D_dockwidget.py", line 253, in retranslateUi
    self._loadHistory()
  File "/home/pesek/.local/share/QGIS/QGIS3/profiles/default/python/plugins/smoderp2d-plugin/smoderp_2D_dockwidget.py", line 492, in _loadHistory
    runs = self.settings.value('historical_runs')
TypeError: unable to convert a C++ 'QVariantList' instance to a Python object
```

**Comment by landam** [comment]
> Now I get `2024-05-24T09:34:13 WARNING TypeError: cannot pickle 'QgsRasterLayer' object` when I ran it in QGIS.

This issue should be addressed by ff31c4cf

**Review by pesekon2 — CHANGES_REQUESTED** [review]
When I load something from the history pane in QGIS, the `Maximum time step [s]` is not updated.

**Review by pesekon2 — CHANGES_REQUESTED** [review]
I know that I am going to be annoying but are you sure it fixes loading `Maximum time step [s]`? Because it does not do so at my side.

**Comment by landam** [comment]
> I know that I am going to be annoying but are you sure it fixes loading `Maximum time step [s]`? Because it does not do so at my side.

It seems to work for me:

[Screencast from 2024-05-28 10-39-32.webm](https://github.com/storm-fsv-cvut/smoderp2d/assets/5683186/af40f6b0-b203-413c-9e56-4a940fde867c)

BTW, `maxdt` was also missing in test parameters, see b4bd0df.

**Review by pesekon2 — APPROVED** [review]
Looks absolutely astonishing! Thanks for the PR!

(PS: the last issue was on my side, sorri)

**Pull request merged**
