### PR TITLE
streams_f: fix ambiguous while loop

### LINKED ISSUE #169: Computation in ArcGIS fails
```py
C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\processes\infiltration\__init__.py:49: RuntimeWarning: divide by zero encountered in true_divide
  infiltration = (0.5 * s / ma.sqrt(totalT + deltaT) + k) * deltaT
C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\processes\infiltration\__init__.py:49: RuntimeWarning: invalid value encountered in true_divide
  infiltration = (0.5 * s / ma.sqrt(totalT + deltaT) + k) * deltaT
Traceback (most recent call last):
  File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\test_arcgis.py", line 27, in <module>
    perform_dpre_ref_test(ArcGisRunner, dpre_params, dataprep_only=False)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\dpre_utils.py", line 85, in perform_dpre_ref_test
    runner.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\__init__.py", line 101, in run
    runoff.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\runoff.py", line 361, in run
    self.surface.stream_reach_outflow(self.delta_t)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\core\stream.py", line 106, in stream_reach_outflow
    r.outflow_method(r, dt)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\stream_functions\stream_f.py", line 162, in triangle
    he = compute_h(A=Ve / reach.length, m=reach.m, b=B)  # funkce pouzita pro lichobeznik  ____
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\stream_functions\stream_f.py", line 40, in compute_h
    while feval(h_pre) > err:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### PR DESCRIPTION
**Pull request by pesekon2**
fix #169

### CODE REVIEW

**Comment by landam** [comment]
@pesekon2 Next error:

```py
C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\processes\infiltration\__init__.py:49: RuntimeWarning: divide by zero encountered in true_divide
  infiltration = (0.5 * s / ma.sqrt(totalT + deltaT) + k) * deltaT
C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\processes\infiltration\__init__.py:49: RuntimeWarning: invalid value encountered in true_divide
  infiltration = (0.5 * s / ma.sqrt(totalT + deltaT) + k) * deltaT
Traceback (most recent call last):
  File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\test_arcgis.py", line 27, in <module>
    perform_dpre_ref_test(ArcGisRunner, dpre_params, dataprep_only=False)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\dpre_utils.py", line 85, in perform_dpre_ref_test
    runner.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\__init__.py", line 101, in run
    runoff.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\runoff.py", line 361, in run
    self.surface.stream_reach_outflow(self.delta_t)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\core\stream.py", line 106, in stream_reach_outflow
    r.outflow_method(r, dt)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\stream_functions\stream_f.py", line 178, in triangle
    reach.vs = math.pow(
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\numpy\ma\core.py", line 4363, in __float__
    raise TypeError("Only length-1 arrays can be converted "
TypeError: Only length-1 arrays can be converted to Python scalars
```

**Review by landam — CHANGES_REQUESTED** [review]
See comment above.

**Comment by pesekon2** [comment]
> @pesekon2 Next error:
> 
> ```python
> C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\processes\infiltration\__init__.py:49: RuntimeWarning: divide by zero encountered in true_divide
>   infiltration = (0.5 * s / ma.sqrt(totalT + deltaT) + k) * deltaT
> C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\processes\infiltration\__init__.py:49: RuntimeWarning: invalid value encountered in true_divide
>   infiltration = (0.5 * s / ma.sqrt(totalT + deltaT) + k) * deltaT
> Traceback (most recent call last):
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\test_arcgis.py", line 27, in <module>
>     perform_dpre_ref_test(ArcGisRunner, dpre_params, dataprep_only=False)
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\tests\dpre_utils.py", line 85, in perform_dpre_ref_test
>     runner.run()
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\__init__.py", line 101, in run
>     runoff.run()
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\runoff.py", line 361, in run
>     self.surface.stream_reach_outflow(self.delta_t)
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\core\stream.py", line 106, in stream_reach_outflow
>     r.outflow_method(r, dt)
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\stream_functions\stream_f.py", line 178, in triangle
>     reach.vs = math.pow(
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\numpy\ma\core.py", line 4363, in __float__
>     raise TypeError("Only length-1 arrays can be converted "
> TypeError: Only length-1 arrays can be converted to Python scalars
> ```

@landam This was solved last week in master. I have merged master into this branch. Try again, please.

**Comment by pesekon2** [comment]
> Error in GRASS:
> 
> ```python
> Traceback (most recent call last):
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/./bin/grass/r.smoderp2d/r.smoderp2d.py", line 147, in <module>
>     runner.run()
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/./bin/grass/r.smoderp2d/../../../smoderp2d/__init__.py", line 101, in run
>     runoff.run()
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/./bin/grass/r.smoderp2d/../../../smoderp2d/runoff.py", line 361, in run
>     self.surface.stream_reach_outflow(self.delta_t)
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/./bin/grass/r.smoderp2d/../../../smoderp2d/core/stream.py", line 106, in stream_reach_outflow
>     r.outflow_method(r, dt)
>   File "/home/martin/git/storm-fsv-cvut/smoderp2d/./bin/grass/r.smoderp2d/../../../smoderp2d/stream_functions/stream_f.py", line 75, in rectangle
>     reach.vs = ma.pow(
>                ^^^^^^
> AttributeError: module 'numpy.ma' has no attribute 'pow'
> ```

@landam: Solved in [1f0731f](https://github.com/storm-fsv-cvut/smoderp2d/pull/172/commits/1f0731f1f0165b2a48507484b5af3ce84d60692e)

**Pull request merged**
