### PR TITLE
Tests: numerical comparision instead of string-based

### PR DESCRIPTION
**Pull request by landam**

### CODE REVIEW

**Comment by landam** [comment]
# Rain_sim differences

```
-array_points:[[ 1.          1.          2.          1.16349162  7.30944235]
 [ 2.         13.          2.          1.37450624  1.4115917 ]
 [ 3.         14.          3.          1.83445206  0.82906839]
 [ 4.         15.          0.          0.257301    0.26458773]
 [ 5.         15.          3.          1.84874634  0.28907763]
 [ 6.         14.          2.          1.34529389  0.80651487]]
+array_points:[[ 1.      1.      2.      1.1635  7.3094]
 [ 2.     13.      2.      1.3745  1.4116]
 [ 3.     14.      3.      1.8345  0.8291]
 [ 4.     15.      0.      0.2573  0.2646]
 [ 5.     15.      3.      1.8487  0.2891]
 [ 6.     14.      2.      1.3453  0.8065]]
```

```
-mat_effect_cont:[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
+mat_effect_cont:[[0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]
 [0.50000006 0.50000006 0.50000006 0.50000006]]
```

```
-mat_pi:[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-mat_ppl:[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
+mat_pi:[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
+mat_ppl:[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
```

```
-streams:{'stream_segment_id': [1], 'channel_shape_id': [2], 'stream_segment_next_down_id': [-1], 'stream_segment_length': [1.352399640264292], 'stream_segment_inclination': [0.1629760178093945], 'channel_profile': ['rectangle1'], 'channel_shapetype': [0], 'channel_bottom_width': [0.2], 'channel_bank_steepness': [0.0], 'channel_bed_roughness': [0.035], 'channel_q365': [0]}
+streams:{'stream_segment_id': [1], 'channel_shape_id': [2], 'stream_segment_next_down_id': [-1], 'stream_segment_length': [1.35236357684681], 'stream_segment_inclination': [0.16298036388338705], 'channel_profile': ['rectangle1'], 'channel_shapetype': [0], 'channel_bottom_width': [0.2], 'channel_bank_steepness': [0.0], 'channel_bed_roughness': [0.035], 'channel_q365': [0]}
```

```
-xllcorner:0.1
-yllcorner:0.1
+xllcorner:0.09999999999999998
+yllcorner:0.09999999999999964
```

**Comment by pesekon2** [comment]
@landam: It works, it just reports full diffs when something is wrong (yes, this could be taken care of one day). I found the difference in control points. See this for point001: 

```diff
-1.8011e+02;1.1085e-01;3.3219e-06;1.9284e-04;2.3141e-04;2.5652e-05;2.4000e+00;2.2558e-05;2.4039e-07;0.0000e+00;1.0000e+00;7.7847e-05;8.2687e-04;6.3095e-04;2.1229e-02;4.7085e-04;5.2195e-05;1.4925e+00;1.0554e-04;7.0225e-04;7.7847e-05;2.7105e-20;1.5774e-04;0.0000e+00;9.5000e-01;0.0000e+00;2.0000e+00
+1.8011e+02;1.1085e-01;3.3219e-06;1.9284e-04;2.3141e-04;2.5652e-05;2.4000e+00;2.2558e-05;2.4039e-07;0.0000e+00;1.0000e+00;7.7847e-05;8.2687e-04;6.3095e-04;2.1229e-02;4.7085e-04;5.2195e-05;1.4925e+00;1.0554e-04;7.0225e-04;7.7847e-05;-2.7105e-20;1.5774e-04;0.0000e+00;9.5000e-01;0.0000e+00;2.0000e+00
```

Any idea how did that minus slip in?

**Comment by pesekon2** [comment]
Another thing I could see is that the difference between ArcGIS and GRASS is not within five valid digits for point002:

```diff
-1.8022e+02;1.1085e-01;3.3219e-06;1.9284e-04;2.3141e-04;2.5652e-05;2.4000e+00;2.2558e-05;2.4038e-07;0.0000e+00;1.0000e+00;7.8187e-05;8.2995e-04;6.3403e-04;2.1281e-02;4.7392e-04;5.2535e-05;1.4949e+00;1.0597e-04;7.0532e-04;7.8187e-05;0.0000e+00;1.5851e-04;0.0000e+00;9.5000e-01;0.0000e+00;1.0000e+00
+1.8022e+02;1.1085e-01;3.3219e-06;1.9284e-04;2.3141e-04;2.5652e-05;2.4000e+00;2.2558e-05;2.4038e-07;0.0000e+00;1.0000e+00;7.8187e-05;8.2995e-04;6.3403e-04;2.1281e-02;4.7391e-04;5.2535e-05;1.4949e+00;1.0597e-04;7.0532e-04;7.8187e-05;0.0000e+00;1.5851e-04;0.0000e+00;9.5000e-01;0.0000e+00;1.0000e+00
```

**Comment by pesekon2** [comment]
> (yes, this could be taken care of one day)

Taken care of in [f18ada1](https://github.com/storm-fsv-cvut/smoderp2d/pull/310/commits/f18ada1e413513da315c57517c662cb7c508ae4f)

**Review by pesekon2 — APPROVED** [review]

**Pull request merged**
