### PR TITLE
ArcGIS / GRASS provider major rewrite

### PR DESCRIPTION
**Pull request by landam**
Remaining tasks:

- [x] @pesekon2 improve pickle testing https://github.com/storm-fsv-cvut/smoderp2d/blob/jandevaty-patch-1/tests/dpre_utils.py#L29
- [x] rewrite GRASS provider
- [x] arcgis: check dpre.save.diff and explain differences compared to the previous (master) version

### CODE REVIEW

**Comment by landam** [comment]
@jandevaty I tested ArcGIS provider, it seems to work. But computation fails:

```py
Traceback (most recent call last):
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\SMODERP2D_cmd.py", line 50, in <module>
    run_smoderp2d(parameters)
  File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\SMODERP2D_cmd.py", line 20, in run_smoderp2d
    runner.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\__init__.py", line 84, in run
    self._provider.load()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\base\__init__.py", line 232, in load
    data = self._load_dpre()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\arcgis\__init__.py", line 135, in _load_dpre
    return prep.run()
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\base\data_preparation.py", line 119, in run
    self._get_inf_combinat_index(self.data['r'], self.data['c'],
  File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\base\data_preparation.py", line 320, in _get_inf_combinat_index
    kkk = mat_k[i][j]
IndexError: index 123 is out of bounds for axis 0 with size 123
```

**Comment by landam** [comment]
@jandevaty Please clean up `test/data` directory. There are duplicated files:

* `landuse` and `landuse_`
* `soil` and `soil_`
* `soil_veg_tab_mean` and `soil_veg_tab_mean_`

Keep in the data directory only one version.

**Comment by jandevaty** [comment]
> @jandevaty Please clean up `test/data` directory. There are duplicated files:
> 
>     * `landuse` and `landuse_`
> 
>     * `soil` and `soil_`
> 
>     * `soil_veg_tab_mean` and `soil_veg_tab_mean_`
> 
> 
> Keep in the data directory only one version.

Those "duplicates with underscore" were created as intentionally faulty versions of the input files to test consistency checks in the data preparation ... but can be removed, no problem

**Comment by landam** [comment]
> @jandevaty I tested ArcGIS provider, currently it fails with:
> 
> ```python
> Traceback (most recent call last):
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\SMODERP2D_cmd.py", line 50, in <module>
>     run_smoderp2d(parameters)
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\bin\arcgis\SMODERP2D_cmd.py", line 20, in run_smoderp2d
>     runner.run()
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\__init__.py", line 84, in run
>     self._provider.load()
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\base\__init__.py", line 232, in load
>     data = self._load_dpre()
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\arcgis\__init__.py", line 135, in _load_dpre
>     return prep.run()
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\base\data_preparation.py", line 119, in run
>     self._get_inf_combinat_index(self.data['r'], self.data['c'],
>   File "C:\Users\martin\Documents\GitHub\smoderp2d\smoderp2d\providers\base\data_preparation.py", line 320, in _get_inf_combinat_index
>     kkk = mat_k[i][j]
> IndexError: index 123 is out of bounds for axis 0 with size 123
> ```
> 
> @jerabekjak The error seems to be related to a new mask based on slope... (?)

I changed code to indicate where is a source of the problem: https://github.com/storm-fsv-cvut/smoderp2d/blob/jandevaty-patch-1/smoderp2d/providers/arcgis/data_preparation.py#L267

Now it fails with:

```py
ERROR: Unexpected array k dimension ((77, 123)): should be (78, 124)
Unexpected array k dimension ((77, 123)): should be (78, 124)
```

@jandevaty Any idea why numpy arrays are created with different number of rows and columns than expected (https://github.com/storm-fsv-cvut/smoderp2d/blob/jandevaty-patch-1/smoderp2d/providers/arcgis/data_preparation.py#L303)

**Comment by landam** [comment]
Problem je v rasterizaci, vysledny rastr nema shodnou referenci s AOI maskou.

VirtualBox_MS Windows_21_12_2022_18_42_09

**Comment by landam** [comment]
> Problem je v rasterizaci, vysledny rastr nema shodnou referenci s AOI maskou.

Fixed by https://github.com/storm-fsv-cvut/smoderp2d/pull/143/commits/7689ed898970c18cdcec09d11785219136154cf8

**Comment by landam** [comment]
> Those "duplicates with underscore" were created as intentionally faulty versions of the input files to test consistency checks in the data preparation ... but can be removed, no problem

I took liberty to remove them (31a273f)

**Comment by landam** [comment]
@jandevaty FYI, I renamed `bin/arcgis/SMODERP2D_cmd.py` to `tests/test_arcgis.py`.

**Comment by pesekon2** [comment]
@landam: Signatures of methods in [ArcGIS data preparation](https://github.com/storm-fsv-cvut/smoderp2d/blob/39185d8a52ce1ebc53cb0d4f97d1f2218f53e422/smoderp2d/providers/arcgis/data_preparation.py) do not correspond to the signature of their abstract parents [in base](https://github.com/storm-fsv-cvut/smoderp2d/blob/39185d8a52ce1ebc53cb0d4f97d1f2218f53e422/smoderp2d/providers/base/data_preparation.py), breaking the Liskov substitution principle. Either add `**kwargs` to the base provider or (I believe better) make them correspond (add the arguments to the abstract definition).

**Comment by pesekon2** [comment]
@landam: Results from `test_arcgis.py` and `test_grass.py` should be in a readable format now.

**Comment by landam** [comment]
> Signatures of methods in [ArcGIS data preparation](https://github.com/storm-fsv-cvut/smoderp2d/blob/39185d8a52ce1ebc53cb0d4f97d1f2218f53e422/smoderp2d/providers/arcgis/data_preparation.py) do not correspond to the signature of their abstract parents [in base](https://github.com/storm-fsv-cvut/smoderp2d/blob/39185d8a52ce1ebc53cb0d4f97d1f2218f53e422/smoderp2d/providers/base/data_preparation.py), breaking the Liskov substitution principle. Either add `**kwargs` to the base provider or (I believe better) make them correspond (add the arguments to the abstract definition).

@pesekon2 Should be solved by 3c2ab46

**Comment by landam** [comment]
> @landam: Results from `test_arcgis.py` and `test_grass.py` should be in a readable format now.

Currently variables are not printed one after each other, eg.

```
-mat_a:[[-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 ...
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]]
-mat_aa:[[-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 ...
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]]
-mat_b:[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
+mat_a:[[-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 ...
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]]
+mat_aa:[[-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 ...
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]]
+mat_b:[[-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 ...
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]]
```

Expected order:
```
-mat_a:[[-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 ...
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]]
+mat_a:[[-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 ...
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]]
-mat_aa:[[-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 ...
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]
 [-9999. -9999. -9999. ... -9999. -9999. -9999.]]
+mat_aa:[[-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 ...
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]
 [-3.40282347e+38 -3.40282347e+38 -3.40282347e+38 ... -3.40282347e+38
  -3.40282347e+38 -3.40282347e+38]]
-mat_b:[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
+mat_b:[[-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 ...
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]
 [-3.4028235e+38 -3.4028235e+38 -3.4028235e+38 ... -3.4028235e+38
  -3.4028235e+38 -3.4028235e+38]]
```

@pesekon2 Please modify the code accordingly.

**Comment by pesekon2** [comment]
> @pesekon2 Please modify the code accordingly.

@landam: Are you sure you want me to modify it to work the way you proposed? The current style is the recommended unified diff format used by commands such as `git diff` and even the basic `diff`. If a chunk of consecutive lines is modified, then the entire chunk is reported (to see the difference in context). However, if you wish to, I can do so - `difflib` doesn't support such behaviour, so we would need to parse the two files line by line manually, but it can be done.

**Comment by landam** [comment]
> @landam: Are you sure you want me to modify it to work the way you proposed? The current style is the recommended unified diff format used by commands such as `git diff` and even the basic `diff`. If a chunk of consecutive lines is modified, then the entire chunk is reported (to see the difference in context). However, if you wish to, I can do so - `difflib` doesn't support such behaviour, so we would need to parse the two files line by line manually, but it can be done.

OK, so let's keep current behaviour.

**Pull request merged**
